name: "Hello World Workflow"


#Controls when action will run. This will trigger the workflow on push something to main or production branch.
on:
  push:
    branches:
      - main
      - production

jobs:
  hello_world:   #This is job name
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"