name: "Multi Event Pipeline / Workflow"  #Name of pipeline

on:
    push:   # Event: Whenever a push is made to the repo on the main / test branch
        branches:
            - main
            - test
            - newtest
    pull_request:   #Event whenever a pull request is made to the repo.
        branches:
            - main
            - newtest
        types:    #Another sub-event to define type
            - closed      
    workflow_dispatch: # Gives us manual control to run workflow from github.com
            

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main/test push"
              run: echo "Running on test/main branch"

    on-pull_request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running a pull request"
              run: echo "Running a pull request"    
    
    on-workflow_dispatch:   #job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on workflow dispatch"
              run: echo "Running on Workflow dispatch"

    on-pull_request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on closed pull request"
              run: echo "Running on Pull request closed"

              

            
            

    
        
        
             
                
  